# Archivo de configuración de infraestructura completa
resource "local_file" "infrastructure_summary" {
  filename = "${local.resource_prefix}-infrastructure.json"
  content = jsonencode({
    project_info = {
      name         = var.app_name
      environment  = var.environment
      created_at   = local.creation_timestamp
      resource_prefix = local.resource_prefix
    }
    
    infrastructure = local.infrastructure_config
    security       = local.security_config
    cost_analysis  = local.cost_analysis
    features       = local.enabled_features
    components     = local.application_components
  })
}

# Archivo de configuración por componente
resource "local_file" "component_configs" {
  for_each = local.application_components
  
  filename = "components/${each.key}-${var.environment}.yaml"
  content = templatefile("${path.module}/templates/component.yaml.tpl", {
    component_name = each.key
    component_config = each.value
    environment = var.environment
    tags = local.common_tags
    security_group = local.security_groups[each.key]
  })
}

# Terraform workspace summary
resource "local_file" "workspace_summary" {
  filename = "${local.resource_prefix}-summary.txt"
  content = <<-EOF
    🚀 TERRAFORM WORKSPACE SUMMARY
    ================================
    
    📋 PROJECT INFORMATION
    Name: ${var.app_name}
    Environment: ${upper(var.environment)}
    Created: ${local.readable_date}
    Resource Prefix: ${local.resource_prefix}
    
    🏗️ INFRASTRUCTURE
    VPC CIDR: ${local.infrastructure_config.networking.vpc_cidr}
    Instance Type: ${local.infrastructure_config.compute.instance_type}
    Min Replicas: ${local.current_env.min_replicas}
    Max Replicas: ${local.current_env.max_replicas}
    
    💾 DATABASE
    Engine: ${var.database_config.engine}
    Instance Class: ${local.infrastructure_config.database.instance_class}
    Storage: ${local.infrastructure_config.database.allocated_storage}GB
    Multi-AZ: ${local.infrastructure_config.database.multi_az}
    
    🎛️ FEATURES ENABLED
    %{ for feature, enabled in local.enabled_features ~}
    %{ if enabled ~}
    ✅ ${title(feature)}
    %{ endif ~}
    %{ endfor ~}
    
    📊 RESOURCE ALLOCATION
    Total vCPUs: ${local.cost_analysis.total_resources.vcpus}
    Total Memory: ${local.cost_analysis.total_resources.memory_gb}GB
    Total Storage: ${local.cost_analysis.total_resources.storage_gb}GB
    
    💰 COST ESTIMATION (Monthly)
    Compute: $${local.cost_analysis.monthly_costs.compute}
    Database: $${local.cost_analysis.monthly_costs.database}
    Storage: $${local.cost_analysis.monthly_costs.storage}
    Network: $${local.cost_analysis.monthly_costs.network}
    ──────────────────────────────
    TOTAL: $${local.cost_analysis.total_monthly_estimate}
    
    🏷️ COMMON TAGS
    %{ for key, value in local.common_tags ~}
    ${key}: ${value}
    %{ endfor ~}
    
    ──────────────────────────────
    Generated by Terraform 🤖
  EOF
}