{
 "title": "Custom App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pods Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod)(up{job=\"mi-app-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage por Pod (K8s metrics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=\"mi-app\"}/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users por Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum by (pod)(app_active_users)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests por Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod,endpoint,status)(rate(app_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage por Pod (K8s metrics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"mi-app\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time por Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le, pod, endpoint)(histogram_quantile(0.95, rate(app_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}