{
 "title": "Métricas del Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pods por estado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployments con réplicas deseadas vs disponible",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available / kube_deployment_status_replicas",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top namespaces por CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total[1m])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top pods por memoria",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "topk(10, container_memory_working_set_bytes{container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}