apiVersion: v1
kind: Namespace
metadata:
  name: tienda-dev
  labels:
    proyecto: tienda-online
    ambiente: desarrollo

---
apiVersion: v1
kind: Namespace
metadata:
  name: tienda-prod
  labels:
    proyecto: tienda-online
    ambiente: produccion