apiVersion: v1
clusters:
- cluster:
    #certificate-authority-data: KEY_BASE64
    insecure-skip-tls-verify: true
    server: http://127.0.0.1:9595
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: KEY_BASE64
    client-key-data: KEY_BASE64
