apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  package.json: |
    {
      "name": "mi-app",
      "version": "1.0.0",
      "scripts": {
        "start": "node server.js"
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secrets
type: Opaque
stringData:
  JWT_SECRET: "mi-super-secret"
  API_KEY: "abcd-1234-efgh-5678"
  API_REST: "http://api:3000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        
        envFrom:
        - configMapRef:
            name: nginx-config
        - secretRef:
            name: nginx-secrets
        
        volumeMounts:
        - name: app-config
          mountPath: /app/config
        - name: app-secrets
          mountPath: /app/secrets
        
      volumes:
        - name: app-config
          configMap:
            name: nginx-config
        - name: app-secrets
          secret:
            secretName: nginx-secrets
            defaultMode: 0400