apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting-app
  labels:
    project: vote-app
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: vote:latest
        ports:
          - containerPort: 5000
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: vote-config
                key: redis_host
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: vote-config
                key: postgres_host
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: vote-secrets
                key: postgres_user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vote-secrets
                key: postgres_pwd
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: vote-config
                key: postgres_db
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: voting-app
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000