replicaCount: 3
image:
  repository: nginx
  tag: "1.21"
service:
  type: LoadBalancer
resources:
  limits:
    cpu: 200m
    memory: 256Mi
serviceAccount:
  create: false       # ← Esto está causando el error
  name: default  # ← Probablemente definido en tus `values-prod.yaml`