# Deployment en namespace de desarrollo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: mi-app-dev  # ← Aquí especificamos el namespace
spec:
  replicas: 1  # Solo 1 réplica en dev
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        ambiente: desarrollo
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80

---
# Service para acceder a la aplicación
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: mi-app-dev  # ← Mismo namespace
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    nodePort: 30100
  type: NodePort