services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl -h http://localhost:3000/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"