{
 "title": "Dashboard App python",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Endpoint more uses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(app_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Last 5min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(app_requests_total[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "User actives top 5",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(5, app_user_access_total)", "legendFormat": "{{user_id}}" }
   ]
  },
  {
   "title": "Response Time P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(app_request_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login success vd fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(app_requests_total{endpoint=\"/api/login\", status=\"200\"}[5m])",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "rate(app_requests_total{endpoint=\"/api/login\", status=\"401\"}[5m]) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(app_requests_total{status!=\"200\"}[1m]) / rate(app_requests_total[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Access by User",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_user_access_total", "legendFormat": "{{user_id}}" }
   ]
  },
  {
   "title": "Errors by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "rate(app_errors_total[1m])", "legendFormat": "{{endpoint}} - {{error_type}}" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_active_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "{{endpoint}} - {{status}}" }
   ]
  }
 ]
}