Vagrant.configure("2") do |config|
  # Usa una imagen ligera de Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"

  # Configuración de red (accesible via IP)
  config.vm.network "private_network", ip: "192.168.33.10"

  # Provisionamiento con Shell
  config.vm.provision "docker", type:"shell", path: "./scripts/instalar_docker.sh"
  config.vm.provision "kubernetes", type:"shell", path: "./scripts/instalar_kubernetes.sh"
  config.vm.provision "node", type:"shell", path: "./scripts/instalar_node.sh"
end