- name: Crear grupo devops si no existe
  group:
    name: devops
    state: present

- name: Crear usuario devops con grupo propio
  user:
    name: devops
    state: present
    shell: /bin/bash
    groups: sudo
    create_home: yes

- name: Crear carpeta .ssh
  file:
    path: /home/devops/.ssh
    state: directory
    owner: devops
    group: devops
    mode: '0700'

- name: Generar par de llaves SSH para devops
  community.crypto.openssh_keypair:
    path: /home/devops/.ssh/id_rsa
    type: rsa
    size: 2048
    owner: devops
    group: devops
    mode: '0600'
    force: no

- name: Autorizar clave pública
  copy:
    src: /home/devops/.ssh/id_rsa.pub
    dest: /home/devops/.ssh/authorized_keys
    owner: devops
    group: devops
    mode: '0600'
    remote_src: yes