- name: instalar python
  ansible.builtin.package:
    name: 
      - python3
      - python3-pip
      - python3-venv
      - python3-psycopg2
    state: present

- name: Crear entorno virtual si no existe
  ansible.builtin.command:
    cmd: python3 -m venv venv
    chdir: "{{ path_vote }}"
    creates: "{{ path_vote }}/venv/bin/activate"

- name: Instalar requerimientos en el entorno virtual
  ansible.builtin.command:
    cmd: ./venv/bin/pip install -r requirements.txt
    chdir: "{{ path_vote }}"
