Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  (1..2).each do |i|
    config.vm.define "web#{i}" do |web|
      web.vm.hostname = "web#{i}"
      web.vm.network "private_network", ip: "192.168.33.1#{i}"
      web.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y ansible
        ansible-playbook /vagrant/playbook.yml -e "env=dev"
      SHELL
    end
  end
  
  config.vm.define "loadbalancer" do |lb|
    lb.vm.hostname = "loadbalancer"
    lb.vm.network "private_network", ip: "192.168.33.10"

    lb.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y ansible
      ansible-galaxy collection install community.crypto
      ansible-playbook /vagrant/playbook.yml -e "env=prod"
    SHELL
      
  end
  
end