---
- name: Despliegue de voteapp
  hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - import_tasks: roles/git/tasks/main.yml
    - import_tasks: roles/python/tasks/main.yml
    - import_tasks: roles/redis/tasks/main.yml
    - import_tasks: roles/postgresql/tasks/main.yml
    - import_tasks: roles/nodejs/tasks/main.yml