Vagrant.configure("2") do |config|
  #VM1
  config.vm.define "ansible" do |ansible|
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", ip: "192.168.15.10"
    config.vm.provision "instalar ansible", type: "shell", path: "./scripts/instalar_ansible.sh"
  end

   #VM2
   config.vm.define "web" do |web|
     config.vm.box = "ubuntu/jammy64"
     config.vm.network "private_network", ip: "192.168.16.10"
     config.vm.provision "instalar nginx", type: "shell", path: "./scripts/instalar_nginx.sh"
   end
   
   config.vm.define "web2" do |web2|
     config.vm.box = "ubuntu/jammy64"
     config.vm.network "private_network", ip: "192.168.17.10"
   end

#   #VM4
#   config.vm.define "db" do |db|
#     config.vm.box = "ubuntu/jammy64"
#     # Configuración de red (accesible via IP)
#     config.vm.network "private_network", ip: "192.168.17.10"
#     # Provisionamiento con Shell
#     config.vm.provision "instalar ansible", type: "shell", path: "./scripts/instalar_mysql.sh"
#   end
  
end
