Vagrant.configure("2") do |config|
  # Usa una imagen ligera de Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"

  # Configuración de red (accesible via IP)
  config.vm.network "private_network", ip: "192.168.14.10"

  # Provisionamiento con Shell
  config.vm.provision "nginx", type: "shell", path: "./scripts/instalar_nginx.sh"
  config.vm.provision "template", type: "shell", path: "./scripts/instalar_template.sh"
end
