apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config2
data:
  # configuraciones simples 
  database_url: "mysql://db:3306/myapp"
  debug_mode: "true"
  max_connections: "100"
  log_level: "info"

  # Archivo de configuracion completo
  app.properties: |
    server.port=8080
    server.name=mi-app
    cache.enabled=true
    cache.ttl=3600
  
  nginx.conf: |
    server{
      listen 80;
      server_name localhost;
      location / {
        proxy_pass http://backend-service:8080;
      }
    }