name: Vote Deploy
on:
    push:
        branches: [d42_develop]
        paths: [s6/d42/**]
jobs:
    docker-build:
        name: Docker Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Build vote Image
              run: |
                  cd rox-devops-project90/roxs-voting-app/vote
                  docker build -t vote-front:${{ github.sha }} .
            - name: Build worker Image
              run: |
                  cd rox-devops-project90/roxs-voting-app/worker
                  docker build -t worker-backend:${{ github.sha }} .

            - name: Build result Image
              run: |
                  cd rox-devops-project90/roxs-voting-app/result
                  docker build -t vote-frontend:${{ github.sha }} .
    
    deploy:
        name: Docker Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install kubectl & helm
              run: |
                curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                chmod +x kubectl
                sudo mv kubectl /usr/local/bin/
                curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            - name: Create namespace dev-customer
              run: |
                # Setup kubeconfig (requiere KUBE_CONFIG secret)
                mkdir -p $HOME/.kube
                echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
                cd voting-app-k8s
                kubectl apply -f ./01-namespace.yml
            - name: Configure namespace & storage & config & secrets
              run: |
                # Setup kubeconfig (requiere KUBE_CONFIG secret)
                mkdir -p $HOME/.kube
                echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
                cd voting-app-k8s
                kubectl apply -f ./02-storage.yml
                kbectl apply -f ./03-configs-secrets.yml
            - name: Deploy to dev customer
              run: |
                # Setup kubeconfig (requiere KUBE_CONFIG secret)
                mkdir -p $HOME/.kube
                echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
                cd charts
                helm upgrade --install vote . --namespace voting-app \
                  --values ./vote/values.yaml
                  --set vote.image=vote-front:${{ github.sha }} 

                helm upgrade --install worker . --namespace voting-app \
                  --values ./worker/values.yaml
                  --set worker.image=worker-backend:${{ github.sha }} \
                  --set result.image=vote-frontend:${{ github.sha }}

                helm upgrade --install result . --namespace voting-app \
                  --values ./result/values.yaml
                  --set result.image=vote-frontend:${{ github.sha }}
                
                helm repo update
                helm upgrade --install redis bitnami/redis --values ./redis/values-redis.yaml -n voting-app
                helm upgrade --install postgres bitnami/postgresql --values ./postgres/values-postgres.yaml -n voting-app