name: Deploy Staging

on:
    push: 
        branches: [semana0307_develop]
    workflow_dispatch:

jobs:
    deploy-staging:
        runs-on: ["self-hosted"]
        name: Starting deploy staging ....
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Deploy environment staging
              run: |
                cd ./scripts
                chmod +x ./deploy.sh
                ./deploy.sh staging       

            - name: Ver logs de staging
              run: |
                docker compose -f ./docker-compose.staging.yml logs -f 
