name: deploy-staging

on:
    push: 
        branches: [semana0307_develop]
    workflow_dispatch:

jobs:
    integration-test:
        runs-on: ["self-hosted"]
        steps:
            - name: Checkout código
              uses: actions/checkout@v4
            
            - name: Instalar docker
              uses: docker/setup-docker-action@v4
              with:
                daemon-config: |
                    {
                    "debug": true,
                    "features": {
                        "containerd-snapshotter": true
                      }
                    }
            - name: Desplegar ambiente
              run: |
                chmod +x ../scripts/deploy.sh
                ../scripts/deploy.sh staging       
                docker compose -f ../docker-compose.staging.yml logs -f        
