name: Deploy Production

on:
    pull_request:  
        branches: [semana0307]
    workflow_dispatch:

jobs:
    deploy-production:
        runs-on: ["ubuntu-latest"]
        name: Starting deploy production ....
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup docker
              uses: docker/setup-docker-action@v4
              with:
                daemon-config: |
                    {
                    "debug": true,
                    "features": {
                        "containerd-snapshotter": true
                      }
                    }
            - name: Deploy environment production
              run: |
                cd ./scripts
                chmod +x ./deploy.sh
                ./deploy.sh production
