name: Monitoreo Simple

on:
  schedule:
    - cron: '0 */2 * * *'  # Cada 2 horas
  workflow_dispatch:

jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Parar servicios anteriores
      run: docker compose down -v || true

    - name: Construir servicios
      run: docker compose -f ./app/docker-compose.yml build

    - name: Levantar servicios
      run: docker compose -f ./app/docker-compose.yml up -d

    - name: Chequear estado
      run: |
        curl -f https://localhost:3000/health && echo "✅ App OK" || echo "❌ App caída"
    
    - name: ejecutar script de test
      run: |
        chmod +x ./scripts/check-app.sh
        ./scripts/check-app.sh