apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Valores en base64
  username: YWRtaW4=     # admin
  password: c3VwZXJzZWNyZXRhMTIz  # supersecreta123
  api-key: bXktYXBpLWtleS0xMjM=   # mi-api-key-123
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTi... # certificado en base64
  tls.key: LS0tLS1CRUdJTi... # clave privada en base64