---
- name: Despliegue Fullstack Freelancer
  hosts: localhost
  become: yes
  vars:
    repo_url: "https://github.com/startbootstrap/startbootstrap-freelancer/archive/gh-pages.zip"
    web_root: "/var/www/freelancer"

  tasks:
    - name: Instalar dependencias
      apt:
        name: ["nginx", "unzip", "wget","openssl"]
        state: present
        update_cache: yes

    - name: Crear directorio web
      file:
        path: "{{ web_root }}"
        state: directory
        mode: '0755'

    - name: Descargar template
      get_url:
        url: "{{ repo_url }}"
        dest: "/tmp/freelancer.zip"
        mode: '0644'

    - name: Descomprimir template
      unarchive:
        src: "/tmp/freelancer.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Mover contenido del subdirectorio
      shell: |
        cd /tmp/startbootstrap-freelancer-gh-pages
        cp -r * {{ web_root }}/
        chown -R www-data:www-data {{ web_root }}

    - name: Limpiar archivos temporales
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/freelancer.zip"
        - "/tmp/startbootstrap-freelancer-gh-pages"

    - name: Configurar Nginx
      template:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/freelancer
      notify: Restart Nginx

    - name: Habilitar sitio
      file:
        src: /etc/nginx/sites-available/freelancer
        dest: /etc/nginx/sites-enabled/freelancer
        state: link

    - name: Eliminar default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    # - name: Generar clave privada
    #   community.crypto.openssl_privatekey:
    #     path: /etc/ssl/private/freelancer.key
    #     size: 2048
    #     state: present

    # - name: Generar certificado SSL autofirmado
    #   community.crypto.x509_certificate:
    #     path: /etc/ssl/certs/freelancer.crt
    #     privatekey_path: /etc/ssl/private/freelancer.key
    #     provider: selfsigned
    #     selfsigned_not_before: "+0s"
    #     selfsigned_not_after: "+365d"
    #     state: present
    
    - name: Configurar firewall
      ufw:
        rule: allow
        port: "22,80,443"
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted