Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.33.10"
  
  # Provisionamiento con Ansible
  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "playbook.yml"
  #   ansible.verbose = "v"
  # end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y ansible
    ansible-playbook /vagrant/playbook.yml
  SHELL
end